# Generated by Django 3.0.4 on 2020-04-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_book_publishing_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishingHouse',
        ),
    ]
